In [1]:
pip install kagglehub

Requirement already satisfied: kagglehub in .\venv\Lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in .\venv\Lib\site-packages (from kagglehub) (0.1.21)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from kagglehub) (26.2)
Requirement already satisfied: pyyaml in .\venv\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in .\venv\Lib\site-packages (from kagglehub) (2.33.1)
Requirement already satisfied: tqdm in .\venv\Lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in .\venv\Lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.1)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests->kagglehub) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests->kagglehub) (2026.4.22)
Requirement already satisfied: colorama in .\venv\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import kagglehub
import pandas as pd
import os
import glob
import shutil
import numpy as np

c:\Users\badia\Encrypted_Network_Traffic_Behavioural_Analysis Repo\Encrypted_Network_Traffic_Behavioural_Analysis\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
data_dir = "Data/Raw_Data"
#creates dir if not found
os.makedirs(data_dir, exist_ok=True)

dfs = []

if len(os.listdir(data_dir)) > 0:
    print("Data found locally. Skipping download.")
else:
    download_path = kagglehub.dataset_download("chethuhn/network-intrusion-dataset")
    files = glob.glob(download_path, recursive=True)

    for file in files:
        print(f"Reading: {file}")
        try:
            df = pd.read_csv(file)
            dfs.append(df)
            shutil.copy2(file, data_dir)
        except Exception as e:
            print(f"Error reading {file}: {e}")

    if dfs:
        data = pd.concat(dfs, ignore_index=True)
        data.to_csv("combined_raw_data.csv", index=False)
        print("Success! Data saved in {data_dir}")
    else:
        print("Failed to download and combine.")

Data found locally. Skipping download.

In [4]:
data = pd.read_csv("Data/Raw_Data/combined_raw_data.csv")

In [5]:
data.head(10)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
5,54871,1022,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
6,54925,4,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
7,54925,42,1,1,6,6,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
8,9282,4,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
9,55153,4,2,0,37,0,31,6,18.5,17.67767,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [6]:
data.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='str')

In [7]:
data.drop(columns=[' Packet Length Variance', ' Fwd Header Length.1', ' Bwd PSH Flags', 'Fwd PSH Flags',
                   ' Fwd URG Flags',' Bwd URG Flags','FIN Flag Count',' SYN Flag Count',
                   ' RST Flag Count',' PSH Flag Count',' ACK Flag Count',' URG Flag Count',
                   ' CWE Flag Count',' ECE Flag Count','Fwd Avg Bytes/Bulk',' Fwd Avg Packets/Bulk',
                   ' Fwd Avg Bulk Rate',' Bwd Avg Bytes/Bulk',' Bwd Avg Packets/Bulk','Bwd Avg Bulk Rate',
                   'Subflow Fwd Packets',' Subflow Fwd Bytes',' Subflow Bwd Packets',' Subflow Bwd Bytes',
                   'Init_Win_bytes_forward',' Init_Win_bytes_backward',' act_data_pkt_fwd',' min_seg_size_forward',
                   ' Active Std',' Active Max',' Active Min',' Idle Std',' Idle Max',' Idle Min', ' Fwd IAT Min',
                   'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
                   ' Bwd IAT Max', ' Bwd IAT Min', ' Fwd Header Length',
                   ' Bwd Header Length', ' Down/Up Ratio', ' Avg Fwd Segment Size',
                   ' Avg Bwd Segment Size', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', 'Bwd Packet Length Max',
                   ' Bwd Packet Length Min', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Min Packet Length',
                   ' Max Packet Length', 'Active Mean', 'Idle Mean', ' Destination Port', ' Fwd Packet Length Std',  ' Bwd Packet Length Std',
                   'Fwd Packets/s', ' Bwd Packets/s'], inplace=True)

data.columns

Index([' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Mean', ' Bwd Packet Length Mean', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', ' Packet Length Mean', ' Packet Length Std',
       ' Average Packet Size', ' Label'],
      dtype='str')

In [8]:
data.columns = data.columns.str.strip()
data.columns

Index(['Flow Duration', 'Total Fwd Packets', 'Total Backward Packets',
       'Total Length of Fwd Packets', 'Total Length of Bwd Packets',
       'Fwd Packet Length Mean', 'Bwd Packet Length Mean', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Packet Length Mean', 'Packet Length Std',
       'Average Packet Size', 'Label'],
      dtype='str')

In [9]:
data = data.convert_dtypes()
data.dtypes

c:\Users\badia\Encrypted_Network_Traffic_Behavioural_Analysis Repo\Encrypted_Network_Traffic_Behavioural_Analysis\venv\Lib\site-packages\pandas\core\dtypes\cast.py:968: RuntimeWarning: invalid value encountered in cast
  elif (arr.astype(int) == arr).all():
c:\Users\badia\Encrypted_Network_Traffic_Behavioural_Analysis Repo\Encrypted_Network_Traffic_Behavioural_Analysis\venv\Lib\site-packages\pandas\core\dtypes\cast.py:995: RuntimeWarning: invalid value encountered in cast
  elif (arr.astype(int) == arr).all():

Flow Duration                    Int64
Total Fwd Packets                Int64
Total Backward Packets           Int64
Total Length of Fwd Packets      Int64
Total Length of Bwd Packets      Int64
Fwd Packet Length Mean         Float64
Bwd Packet Length Mean         Float64
Flow Bytes/s                   Float64
Flow Packets/s                 Float64
Flow IAT Mean                  Float64
Flow IAT Std                   Float64
Flow IAT Max                     Int64
Flow IAT Min                     Int64
Packet Length Mean             Float64
Packet Length Std              Float64
Average Packet Size            Float64
Label                           string
dtype: object

In [10]:
data.isna().sum()

Flow Duration                     0
Total Fwd Packets                 0
Total Backward Packets            0
Total Length of Fwd Packets       0
Total Length of Bwd Packets       0
Fwd Packet Length Mean            0
Bwd Packet Length Mean            0
Flow Bytes/s                   1358
Flow Packets/s                    0
Flow IAT Mean                     0
Flow IAT Std                      0
Flow IAT Max                      0
Flow IAT Min                      0
Packet Length Mean                0
Packet Length Std                 0
Average Packet Size               0
Label                             0
dtype: int64

In [11]:
data.isnull().sum()

Flow Duration                     0
Total Fwd Packets                 0
Total Backward Packets            0
Total Length of Fwd Packets       0
Total Length of Bwd Packets       0
Fwd Packet Length Mean            0
Bwd Packet Length Mean            0
Flow Bytes/s                   1358
Flow Packets/s                    0
Flow IAT Mean                     0
Flow IAT Std                      0
Flow IAT Max                      0
Flow IAT Min                      0
Packet Length Mean                0
Packet Length Std                 0
Average Packet Size               0
Label                             0
dtype: int64

In [12]:
data.isnull().sum().sum()
#data.isnull().values.any()

np.int64(1358)

In [13]:
data.isna().sum().sum()

np.int64(1358)

In [14]:
data.replace([np.inf, -np.inf], np.nan, inplace=True)
data.dropna(inplace=True) ###remove

In [15]:
data.isna().sum().sum()
#All NaN/+/-inf is removed

np.int64(0)

In [16]:
data.isnull().sum().sum()
#All NaN/+/-inf is removed

np.int64(0)

In [17]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()
#Removing all duplicates while  keeping one copy

np.int64(0)

In [18]:
data['Label'].value_counts()

Label
BENIGN                        1646079
DoS Hulk                       171977
DDoS                           128013
DoS GoldenEye                   10281
FTP-Patator                      5931
DoS slowloris                    5382
DoS Slowhttptest                 5227
SSH-Patator                      3153
PortScan                         1923
Web Attack � Brute Force         1427
Bot                              1337
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         20
Heartbleed                         11
Name: count, dtype: Int64

In [19]:
data['Label'] = data['Label'].astype(str).str.strip()
data['Label'] = data['Label'].apply(
    lambda x: 'Benign' if x.upper() == 'BENIGN' else 'Malicious'
)

In [20]:
data['Label'].value_counts()
#having only 'benign' and 'malicious as labels'

Label
Benign       1646079
Malicious     335370
Name: count, dtype: int64

In [21]:
data.head(2)

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Mean,Bwd Packet Length Mean,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Packet Length Mean,Packet Length Std,Average Packet Size,Label
0,3,2,0,12,0,6.0,0.0,4000000.0,666666.6667,3.0,0.0,3,3,6.0,0.0,9.0,Benign
1,109,1,1,6,6,6.0,6.0,110091.7431,18348.62385,109.0,0.0,109,109,6.0,0.0,9.0,Benign

In [25]:
#pd.options.display.float_format = '{:5d}'.format

In [33]:
from sklearn.utils import resample
#SAMPLING DATA

# Separate by label
data_benign = data[data['Label'] == 'Benign']
data_malicious = data[data['Label'] == 'Malicious']

# Downsample Benign Label
data_benign_downsampled = resample(data_benign, 
                                 replace=False,    # sample without replacement to avoid duplication, overfitting and uniquness
                                 n_samples=125000, # to match malicious count
                                 random_state=42) 
# Downsample Malicious Label
data_malicious_downsampled = resample(data_malicious, 
                                 replace=False,    # sample without replacement to avoid duplication, overfitting and uniquness
                                 n_samples=125000, # to match benign count
                                 random_state=42) 
# Combine Benign and Malicious
sample_data = pd.concat([data_benign_downsampled, data_malicious_downsampled])

#Shuffle
sample_data = sample_data.sample(frac=1, random_state=42).reset_index(drop=True)

In [34]:
sample_data['Label'].value_counts()

Label
Benign       125000
Malicious    125000
Name: count, dtype: int64

In [35]:
sample_data.to_csv("Data/Sample_Data/sample_data.csv", index=False)